describe('empty spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000')
    cy.get('[data-playecolumn="0"]').click()
    cy.get('[data-playecolumn="1"]').click()
    cy.get('[data-playecolumn="2"]').click()
    cy.get('[data-playecolumn="3"]').click()
    cy.get('[data-playecolumn="4"]').click()
    cy.get('[data-playecolumn="5"]').click()
    cy.get('[data-playecolumn="3"]').click()
    cy.get('[data-playecolumn="2"]').click()
    cy.get('[data-playecolumn="3"]').click()
    cy.get('[data-playecolumn="2"]').click()
    cy.get('[data-playecolumn="3"]').click()

    cy.get(':nth-child(1) > .yelloToken')
    cy.get(':nth-child(2) > .redToken')
    cy.get(':nth-child(3) > .yelloToken')
    cy.get(':nth-child(4) > .redToken')
    cy.get(':nth-child(5) > .yelloToken')
    cy.get(':nth-child(6) > .redToken')
    cy.get(':nth-child(3) > :nth-child(4) > .yelloToken')
    cy.get(':nth-child(4) > :nth-child(3) > .redToken')

    cy.get('button').click()
    cy.get(':nth-child(6) > :nth-child(7) > .noToken')
    cy.get(':nth-child(6) > :nth-child(7) > .noToken')
    cy.get(':nth-child(5) > :nth-child(3) > .noToken')
    cy.get(':nth-child(1) > :nth-child(3) > .noToken')
    cy.get(':nth-child(3) > :nth-child(4) > .noToken')
    cy.get(':nth-child(4) > :nth-child(3) > .noToken')

  })
})